apiVersion: v1
kind: Service
metadata:
  name: mongo-exp-service
  labels:
    appname: mongodb 
    type: exp
spec:
  selector:
    appname: mongodb
    type: exp
  type: NodePort  
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30000
